In [1]:
from sklearn import datasets
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np

In [2]:
df = pd.read_csv('original_data.csv')

In [3]:
df.shape

(53644, 26)

In [4]:
df.head()

userName                       major  researchExp  industryExp  \
0       143saf         Systems and Control            0           18   
1   7790ashish   Manufacturing Engineering            0            0   
2         AB25  (MIS / MSIM / MSIS / MSIT)            0           66   
3     abhijitg                         NaN            0            0   
4  abhijitgang                         MIS            0            0   

  specialization  toeflScore program                 department toeflEssay  \
0       Robotics       112.0      MS  Instrumentation & Control         26   
1            NaN         NaN      MS                          0        NaN   
2            NaN        94.0      MS       Computer Engineering         21   
3            NaN         NaN     NaN                          0        NaN   
4            NaN        81.0      MS                   computer        NaN   

   internExp  ...  termAndYear  confPubs                    ugCollege gmatA  \
0        5.0  ...  Fall - 2015         0  Dharamsinh Desai University   NaN   
1        0.0  ...  Fall - 2013         0                          NaN   NaN   
2        0.0  ...  Fall - 2015         0                     IET DAVV   NaN   
3        0.0  ...          NaN       NaN                          NaN   NaN   
4        0.0  ...  Fall - 2011         0              Pune University   NaN   

    cgpa  gmatQ cgpaScale gmatV                         univName  admit  
0   8.50    NaN        10   NaN  Worcester Polytechnic Institute      1  
1   0.00    NaN         0   NaN  Worcester Polytechnic Institute      1  
2  78.28    NaN       100   NaN  Worcester Polytechnic Institute      1  
3   0.00    NaN         0   NaN  Worcester Polytechnic Institute      1  
4  57.00    NaN       100   NaN  Worcester Polytechnic Institute      1  

[5 rows x 26 columns]

In [5]:
df.columns

Index(['userName', 'major', 'researchExp', 'industryExp', 'specialization',
       'toeflScore', 'program', 'department', 'toeflEssay', 'internExp',
       'greV', 'greQ', 'userProfileLink', 'journalPubs', 'greA', 'topperCgpa',
       'termAndYear', 'confPubs', 'ugCollege', 'gmatA', 'cgpa', 'gmatQ',
       'cgpaScale', 'gmatV', 'univName', 'admit'],
      dtype='object')

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 53644 entries, 0 to 53643
Data columns (total 26 columns):
userName           53644 non-null object
major              53257 non-null object
researchExp        53644 non-null int64
industryExp        53644 non-null int64
specialization     31949 non-null object
toeflScore         49230 non-null float64
program            53322 non-null object
department         53643 non-null object
toeflEssay         11874 non-null object
internExp          53630 non-null float64
greV               52388 non-null float64
greQ               52424 non-null float64
userProfileLink    53644 non-null object
journalPubs        53322 non-null object
greA               50786 non-null float64
topperCgpa         53641 non-null float64
termAndYear        53322 non-null object
confPubs           53322 non-null object
ugCollege          51366 non-null object
gmatA              119 non-null float64
cgpa               53644 non-null float64
gmatQ              123 non

In [7]:
categorical = [var for var in df.columns if df[var].dtype=='O']

print('There are {} categorical variables\n'.format(len(categorical)))

print('The categorical variables are :\n\n', categorical)

There are 12 categorical variables

The categorical variables are :

 ['userName', 'major', 'specialization', 'program', 'department', 'toeflEssay', 'userProfileLink', 'journalPubs', 'termAndYear', 'confPubs', 'ugCollege', 'univName']


In [8]:
df[categorical].head()

userName                       major specialization program  \
0       143saf         Systems and Control       Robotics      MS   
1   7790ashish   Manufacturing Engineering            NaN      MS   
2         AB25  (MIS / MSIM / MSIS / MSIT)            NaN      MS   
3     abhijitg                         NaN            NaN     NaN   
4  abhijitgang                         MIS            NaN      MS   

                  department toeflEssay  \
0  Instrumentation & Control         26   
1                          0        NaN   
2       Computer Engineering         21   
3                          0        NaN   
4                   computer        NaN   

                                     userProfileLink journalPubs  termAndYear  \
0  http://www.edulix.com/unisearch/user.php?uid=2...           0  Fall - 2015   
1  http://www.edulix.com/unisearch/user.php?uid=1...           0  Fall - 2013   
2  http://www.edulix.com/unisearch/user.php?uid=2...           0  Fall - 2015   
3  http://www.edulix.com/unisearch/user.php?uid=1...         NaN          NaN   
4  http://www.edulix.com/unisearch/user.php?uid=1...           0  Fall - 2011   

  confPubs                    ugCollege                         univName  
0        0  Dharamsinh Desai University  Worcester Polytechnic Institute  
1        0                          NaN  Worcester Polytechnic Institute  
2        0                     IET DAVV  Worcester Polytechnic Institute  
3      NaN                          NaN  Worcester Polytechnic Institute  
4        0              Pune University  Worcester Polytechnic Institute

In [9]:
df[categorical].isnull().sum()

userName               0
major                387
specialization     21695
program              322
department             1
toeflEssay         41770
userProfileLink        0
journalPubs          322
termAndYear          322
confPubs             322
ugCollege           2278
univName               0
dtype: int64

In [10]:
df['toeflEssay'].unique()

array(['26', nan, '21', '6', '27', '22', '24', '29', '30', '25', '28',
       '3', '4.5', '5.5', '20', '23', '7.5', '6.5', '5', '99', '4', '0',
       '3.5', ' Chemistry', '2.5', '7', ' Information Technology', '18',
       '2', '10', '41', '19', '60', '45', '4.6', '1.5', '35'],
      dtype=object)

In [11]:
df = df[df['toeflEssay'] != ' Information Technology']

In [12]:
df = df[df['toeflEssay'] != ' Chemistry']

In [13]:
df['admit'].unique()

array([1, 0], dtype=int64)

In [14]:
df['researchExp'].unique()

array([ 0, 10, 12, 15, 53,  6, 17, 24,  4,  7,  9,  2, 30,  1, 36, 48, 11,
        5, 18,  3, 14, 16, 22,  8, 32, 20, 34, 42, 29, 21, 37, 26, 13],
      dtype=int64)

In [15]:
a = df['toeflScore'].unique()
print(a)
print(type(a))

[ 112.   nan   94.   81.  273.  104.   95.  101.  107.   99.   91.   96.
   98.  111.  105.  108.  109.  102.  114.  115.   93.  103.  110.   86.
  117.   85.  113.  106.   89.   97.   90.   84.   92.   80.   79.   87.
  100.   82.  237.  257.    0.   88.   76. 1040.   78.    8.   83.    7.
  119.  116.  277.  270.    6.  297.  287.  280.  267.  275.  118.  120.
  263.  290.    4.  620.  283.  293.  300.   57.  260.   65. 1190.  233.
   11.  170. 1004. 1250.  306.  313.  312.   21.  223.  643.    9.   66.
  253.   77.  250.  256.  322.  326. 1210. 1200.  124. 1070.  240.   74.
   75.  247. 1350.  243.  230.   70.  680.   10.  310.  308.  587.   73.
  235.  307.]
<class 'numpy.ndarray'>


In [16]:
df[categorical].isnull().sum()

userName               0
major                387
specialization     21695
program              322
department             1
toeflEssay         41770
userProfileLink        0
journalPubs          322
termAndYear          322
confPubs             322
ugCollege           2278
univName               0
dtype: int64

In [17]:
for var in categorical:
    
    print(var, ' contains ', len(df[var].unique()), ' labels')

userName  contains  14796  labels
major  contains  245  labels
specialization  contains  3619  labels
program  contains  5  labels
department  contains  1486  labels
toeflEssay  contains  35  labels
userProfileLink  contains  14796  labels
journalPubs  contains  12  labels
termAndYear  contains  55  labels
confPubs  contains  11  labels
ugCollege  contains  1823  labels
univName  contains  54  labels


In [18]:
numerical = [var for var in df.columns if df[var].dtype!='O']

print('There are {} numerical variables\n'.format(len(numerical)))

print('The numerical variables are :', numerical)

There are 14 numerical variables

The numerical variables are : ['researchExp', 'industryExp', 'toeflScore', 'internExp', 'greV', 'greQ', 'greA', 'topperCgpa', 'gmatA', 'cgpa', 'gmatQ', 'cgpaScale', 'gmatV', 'admit']


In [19]:
df[numerical].head()

researchExp  industryExp  toeflScore  internExp   greV   greQ  greA  \
0            0           18       112.0        5.0  160.0  167.0   4.5   
1            0            0         NaN        0.0    NaN    NaN   NaN   
2            0           66        94.0        0.0  146.0  157.0   3.0   
3            0            0         NaN        0.0    NaN    NaN   NaN   
4            0            0        81.0        0.0  420.0  770.0   2.5   

   topperCgpa  gmatA   cgpa  gmatQ  cgpaScale  gmatV  admit  
0         8.9    NaN   8.50    NaN         10    NaN      1  
1         0.0    NaN   0.00    NaN          0    NaN      1  
2        81.0    NaN  78.28    NaN        100    NaN      1  
3         0.0    NaN   0.00    NaN          0    NaN      1  
4        70.0    NaN  57.00    NaN        100    NaN      1

In [20]:
df[numerical].isnull().sum()

researchExp        0
industryExp        0
toeflScore      4414
internExp          3
greV            1256
greQ            1220
greA            2858
topperCgpa         3
gmatA          53514
cgpa               0
gmatQ          53517
cgpaScale          0
gmatV          53519
admit              0
dtype: int64

In [21]:
df = df.drop(['gmatA','gmatQ','gmatV','specialization','department','program',
              'userProfileLink','topperCgpa','termAndYear','userName',
              'industryExp','internExp','confPubs','journalPubs','ugCollege',
              'major','univName'],1)

In [22]:
df.shape

(53633, 9)

In [23]:
df = df.dropna()

In [24]:
numerical = [var for var in df.columns if df[var].dtype!='O']

print('There are {} numerical variables\n'.format(len(numerical)))

print('The numerical variables are :', numerical)

There are 8 numerical variables

The numerical variables are : ['researchExp', 'toeflScore', 'greV', 'greQ', 'greA', 'cgpa', 'cgpaScale', 'admit']


In [25]:
df = df.dropna()

In [26]:
df

researchExp  toeflScore toeflEssay   greV    greQ   greA   cgpa  \
0                0       112.0         26  160.0   167.0    4.5   8.50   
2                0        94.0         21  146.0   157.0    3.0  78.28   
5                0       273.0          6  410.0  1010.0  600.0  52.00   
6                0       104.0         27  150.0   161.0    4.5  62.20   
7                0        95.0         22  147.0   156.0    3.0  52.00   
...            ...         ...        ...    ...     ...    ...    ...   
53631            0        95.0         29  144.0   163.0    3.0  74.83   
53634            0        91.0         22  146.0   160.0    2.5  71.00   
53636            0       116.0         29  157.0   162.0    3.0  63.00   
53639            0        98.0         24  151.0   152.0    3.0  71.00   
53640            0       115.0         30  550.0   800.0    4.5   6.50   

       cgpaScale  admit  
0             10      1  
2            100      1  
5            100      1  
6            100      1  
7            100      1  
...          ...    ...  
53631        100      0  
53634        100      0  
53636        100      0  
53639        100      0  
53640         10      0  

[11506 rows x 9 columns]

In [27]:
df.shape

(11506, 9)

In [28]:
df = df.dropna()

In [29]:
X = df.drop(['admit'], axis=1)

y = df['admit']

In [30]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state = 0)

In [31]:
X_train.shape, X_test.shape

((8054, 8), (3452, 8))

In [32]:
X_train.dtypes

researchExp      int64
toeflScore     float64
toeflEssay      object
greV           float64
greQ           float64
greA           float64
cgpa           float64
cgpaScale        int64
dtype: object

In [33]:
categorical = [col for col in X_train.columns if X_train[col].dtypes == 'O']

categorical

['toeflEssay']

In [34]:
X_train[categorical].isnull().mean()

toeflEssay    0.0
dtype: float64

In [35]:
for col in categorical:
    if X_train[col].isnull().mean()>0:
        print(col, (X_train[col].isnull().mean()))

In [36]:
for df2 in [X_train, X_test]:
    df2['toeflEssay'].fillna(X_train['toeflEssay'].mode()[0], inplace=True) 

C:\Users\ITD-STU\Anaconda3\lib\site-packages\pandas\core\generic.py:6287: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._update_inplace(new_data)


In [37]:
X_train[categorical].isnull().sum()

toeflEssay    0
dtype: int64

In [38]:
X_test[categorical].isnull().sum()

toeflEssay    0
dtype: int64

In [39]:
X_train.isnull().sum()

researchExp    0
toeflScore     0
toeflEssay     0
greV           0
greQ           0
greA           0
cgpa           0
cgpaScale      0
dtype: int64

In [40]:
X_test.isnull().sum()

researchExp    0
toeflScore     0
toeflEssay     0
greV           0
greQ           0
greA           0
cgpa           0
cgpaScale      0
dtype: int64

In [41]:
categorical

['toeflEssay']

In [42]:
X_train[categorical].head()

toeflEssay
19111          6
6313          22
46481         23
52653         25
33262         29

In [43]:
from sklearn.naive_bayes import GaussianNB

In [44]:
gnb = GaussianNB()

In [45]:
gnb.fit(X_train, y_train)

GaussianNB(priors=None)

In [46]:
y_pred = gnb.predict(X_test)

y_pred

array([0, 1, 0, ..., 1, 1, 0], dtype=int64)

In [47]:
from sklearn.metrics import accuracy_score

print('Model accuracy score: {0:0.4f}'. format(accuracy_score(y_test, y_pred)))

Model accuracy score: 0.5072


In [48]:
y_pred_train = gnb.predict(X_train)

y_pred_train

array([1, 0, 0, ..., 0, 1, 0], dtype=int64)

In [49]:
print('Training-set accuracy score: {0:0.4f}'. format(accuracy_score(y_train, y_pred_train)))

Training-set accuracy score: 0.5024


In [50]:
print('Training set score: {:.4f}'.format(gnb.score(X_train, y_train)))

print('Test set score: {:.4f}'.format(gnb.score(X_test, y_test)))

Training set score: 0.5024
Test set score: 0.5072


In [51]:
y_test.value_counts()

0    1743
1    1709
Name: admit, dtype: int64

In [52]:
null_accuracy = (1739/(1739+1669))

print('Null accuracy score: {0:0.4f}'. format(null_accuracy))

Null accuracy score: 0.5103
